services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db

  backend:
    image: pnikola/game-backend:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: ${MONGO_URL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

  frontend:
    image: pnikola/game-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend


volumes:
  mongo-data:
