apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: game-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pnikola/game-backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: admin-username
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: admin-password

        # - name: MONGO_ROOT_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secrets
        #       key: mongo-root-username
        # - name: MONGO_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secrets
        #       key: mongo-root-password

