# k8s/03-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: game-app
data:
  MONGO_URL: "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/mydatabase?replicaSet=rs0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: game-app
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
    net:
      port: 27017
      bindIp: 0.0.0.0