name: Build and Deploy

on:
  push:
    branches: [ dev ]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        platforms: linux/amd64
        tags: |
          pnikola/game-backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        platforms: linux/amd64
        tags: |
          pnikola/game-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{secrets.SSH_PORT}}
        script: |
            cd ~/project
            
            # Download the latest docker-compose-prod.yml
            wget -O docker-compose-prod.yml https://raw.githubusercontent.com/${{ github.repository }}/dev/docker-compose-prod.yml
            
            # Pull latest images
            docker compose -f docker-compose-prod.yml pull
            
            # Stop existing containers
            docker compose -f docker-compose-prod.yml down
            
            # Start with new images
            docker compose -f docker-compose-prod.yml up -d
            
            # Clean up old images
            docker image prune -f